package main

const (
	CONFIG_DEFAULT_SERVER_PORT   = 9412
	CONFIG_DEFAULT_SERVER_DAEMON = false

	CONFIG_DEFAULT_LOG_TO_STD    = true
	CONFIG_DEFAULT_LOG_TO_FILE   = true
	CONFIG_DEFAULT_LOG_VERBOSITY = 0
	CONFIG_DEFAULT_LOG_DIR       = "/tmp/skyEye/center"

	CONFIG_LOG_VERBOSITY_DEBUG   = "DEBUG"
	CONFIG_LOG_VERBOSITY_RELEASE = "RELEASE"
)
