package main

const (
	CONFIG_DEFAULT_SERVER_ADDR = "127.0.0.1:9999"

	CONFIG_DEFAULT_LOG_TO_STD    = true
	CONFIG_DEFAULT_LOG_TO_FILE   = true
	CONFIG_DEFAULT_LOG_VERBOSITY = 0
	CONFIG_DEFAULT_LOG_DIR       = "/tmp/skyEye/agent"

	CONFIG_LOG_VERBOSITY_DEBUG   = "DEBUG"
	CONFIG_LOG_VERBOSITY_RELEASE = "RELEASE"
)
